version: "3"
services:
    homemoney:
        image: "${IMAGE}:${VERSION}"
        container_name: homemoney
        hostname: homemoney
        volumes:
            - ./log:/opt/homemoney/log
            - ./config:/opt/homemoney/config
            - ./work:/opt/homemoney/work
        ports:
            - 8080:8080
