version: "3"
services:
    homemoney:
        image: @image@:@version@
        container_name: homemoney
        hostname: homemoney
        volumes:
            - ./config:/opt/homemoney/config
            - ./log:/opt/homemoney/log
            - ./work:/opt/homemoney/work
        environment:
            - PROFILE=cdek
        ports:
            - 8001:8080
